name: Shark Valley Checker

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install browser
        run: playwright install chromium

      - name: Run checker
        run: python check.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
